### ISSUE TITLE
field_type_of_program is not linked to terminology

### ISSUE THREAD

**Issue by natuk** [Worlding-Public-Cultures/wpc-website#1]
In the `academic_program` content type the field `field_type_of_program` should be linked to terminology and not be a text box so that we can group according to type. What values are expected to go in that field?

**Comment by mbelhu** [comment]
I agree. The `field_type_of_program` values would be undergraduate degrees (MA, PhD, etc) and postgraduate degrees (BA). Also I wonder if we need to include terminology used in different countries and languages or just use a more generic terminology such as undergraduate degree and postgraduate degree.

**Comment by natuk** [comment]
This is now dealt with issue #9 . The field `field_type_of_programme` is switched to entity reference for the terminology.
