### ISSUE TITLE
Authoring entries and editorial process

### ISSUE THREAD

**Issue by mbelhu** [Worlding-Public-Cultures/wpc-website#14]
The researchers would like to track the edits to the data and the different authors (if multiple authors have edited data for the same object). At the moment, I have only enable the `Authored by` field for the main content type to avoid making the forms too long. Are there any recommendations on how to best display this authoring information?

**Comment by natuk** [comment]
Tracking changes is possible with the revision functionality in Drupal. The author and time of each change is recorded automatically. I would suggest the we hide the `Authored by` field by default. And also make sure New Revisions is checked for each content type.

**Comment by natuk** [comment]
BTW, simultaneous editing of Drupal forms is not possible.
