### ISSUE TITLE
Force plain text in certain fields

### ISSUE THREAD

**Issue by natuk** [Worlding-Public-Cultures/wpc-website#16]
At the moment Drupal allowed HTML text to be inserted into fields which should only take plain text. Forcing plain text on fields can be done through the [Allowed Formats](https://www.drupal.org/project/allowed_formats) module. I have installed this and will try to configure as many fields as I can with it. We will leave this one until all of the textfields are configured.

**Comment by mbelhu** [comment]
On the display tab I selected the option to hide the format help text as well.
