### ISSUE TITLE
Add "group of actors" vs "single actor" 

### ISSUE THREAD

**Issue by mbelhu** [Worlding-Public-Cultures/wpc-website#18]
At the moment, it looks like we can only add a group of actors/collective after adding individual actors (see screenshot). It should be possible to add the group of actors/collective since sometimes we only know the group but not the individual actors in that group. 

<img width="934" alt="Screenshot 2021-02-16 at 14 00 08" src="https://user-images.githubusercontent.com/17339959/108072902-61350200-705f-11eb-871c-e5dce77a6d2a.png">

**Comment by natuk** [comment]
Good point. I think we might need to repeat that entry form. So it will appear a) within the actor form and b) within the publication form directly. The risk is that people will be confused when they see i twice. The explanatory text will have to make clear that a group is to be added as an author when the group had collective agency over the publication. If one actor only has agency, then the groups that they belong are only connected to the actor, but not the publication. I.e. if one adds the group through the actor, then the group is *not* connected to the publication.

**Comment by mbelhu** [comment]
This has been solved
