### ISSUE TITLE
Location and country in academic course both link to place

### ISSUE THREAD

**Issue by natuk** [Worlding-Public-Cultures/wpc-website#7]
These two fields:

* field_location
* field_country

link to Place content type. This looks redundant since the location (place) should also include the country. I propose to keep field_location only and update Place to include a geolocation address.

**Comment by mbelhu** [comment]
field_country in some cases duplicates the cultures field (but not always).

**Comment by natuk** [comment]
If visualisation on a map or timeline is needed, then we should merge "historical periods" and "Cultures" into a content type called "Periods" with a link to AAT, geocoordinates and time-span.
If such visualisation is not needed, then we can delete "historical periods" and "Cultures" and simply use these as top terms in the terminology.
The "Country/territory" field is the same as "Periods" in the above option 1. So it can be deleted from the forms.
MH to identify which of the two options is best.

**Comment by natuk** [comment]
OK, period now incorporates culture and territory. Pending still is the discussion on the kind of place information we need to store.

**Comment by natuk** [comment]
Place information is dealt with issue #4 so we can close this one.
