### ISSUE TITLE
Academic title as a vocabulary list

### ISSUE THREAD

**Issue by natuk** [Worlding-Public-Cultures/wpc-website#8]
The filed `field_academic_professional_titl` used in the actor content type is currently free-text. Does it need to be an entity_reference field for terms from the vocabulary?

**Comment by mbelhu** [comment]
I am not sure. It can work with vocabularies of academic and arts related professions but I understand this field would tell individuals' specific positions within an institution with a subject focus, i.e., "Jorge Baldor Curator of Latin American Art" or "Chair of Global Art History". 
I believe there was a research question about understanding people's influence in organisations.

**Comment by natuk** [comment]
The generic terms like "Professor", "Lecturer", etc. we should use this field and link it to terminology. For the more specific titles like "Jorge Baldor Curator of Latin American Art" we can say that the actor belongs to a group with the name "Jorge Baldor Curator of Latin American Art" where every past actor holding this title is a member.
